plugins.security.nodes_dn:
  - "CN=opensearch-node, OU=node, O=Malcolm, ST=ID, C=US"

plugins.security.nodes_dn_dynamic_config_enabled: false

plugins.security.authcz.admin_dn:
  - "CN=opensearch-admin, OU=admin, O=Malcolm, ST=ID, C=US"

plugins.security.roles_mapping_resolution: MAPPING_ONLY

plugins.security.audit.enable_rest: false
plugins.security.audit.enable_transport: false
plugins.security.audit.type: internal_opensearch
