---
_meta:
  type: "rolesmapping"
  config_version: 2

all_access:
  reserved: true
  backend_roles:
  - "admin"

logstash:
  reserved: true
  backend_roles:
  - "logstash"

kibana_user:
  reserved: true
  backend_roles:
  - "kibanauser"

readall:
  reserved: true
  backend_roles:
  - "readall"

kibana_server:
  reserved: true
  users:
  - "kibanaserver"
